{
  "openapi": "3.0.0",
  "info": {
    "title": "Image Server",
    "version": "1.0",
    "contact": {},
    "description": ""
  },
  "servers": [
    {
      "url": "https://imageserver.scalecommerce.cloud",
      "variables": {},
      "description": "Staging"
    },
    {
      "url": "http://imageserver.local",
      "description": "Local"
    }
  ],
  "paths": {
    "/api/v1/project/accept": {
      "post": {
        "tags": [
          "Project"
        ],
        "summary": "Accept Project",
        "operationId": "AcceptProject",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LeaveProjectRequest"
              },
              "example": {
                "uuid": "0f67e1a0-0260-4dcf-b667-c8226d12d9a4"
              }
            }
          },
          "required": true,
          "x-send-file-in-body": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/api/v1/project/leave": {
      "post": {
        "tags": [
          "Project"
        ],
        "summary": "Leave Project",
        "operationId": "LeaveProject",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LeaveProjectRequest"
              },
              "example": {
                "uuid": "0f67e1a0-0260-4dcf-b667-c8226d12d9a4"
              }
            }
          },
          "required": true,
          "x-send-file-in-body": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/api/v1/project/delete": {
      "post": {
        "tags": [
          "Project"
        ],
        "summary": "Delete Project",
        "operationId": "DeleteProject",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteProjectRequest"
              },
              "example": {
                "uuid": "0f67e1a0-0260-4dcf-b667-c8226d12d9a4"
              }
            }
          },
          "required": true,
          "x-send-file-in-body": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 1
                    },
                    "message": {
                      "type": "string",
                      "description": "Present if there is any error"
                    }
                  },
                  "required": [
                    "error"
                  ]
                },
                "examples": {
                  "Success": {
                    "value": {
                      "error": 0
                    }
                  },
                  "Error": {
                    "value": {
                      "error": 1,
                      "message": "Project not found"
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": [
          {
            "API Token": []
          }
        ],
        "description": "Delete project"
      },
      "parameters": []
    },
    "/api/v1/project/save": {
      "post": {
        "tags": [
          "Project"
        ],
        "summary": "Create Project",
        "operationId": "CreateProject",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateProjectRequest"
              },
              "example": {
                "name": "lazada.com.vn"
              },
              "examples": {}
            }
          },
          "required": true,
          "x-send-file-in-body": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "project": {
                      "$ref": "#/components/schemas/Project"
                    },
                    "error": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 1
                    }
                  }
                },
                "examples": {
                  "Failed": {
                    "value": {
                      "error": 1,
                      "fields": {
                        "name": "\"example.com\" is already taken."
                      }
                    }
                  },
                  "Success": {
                    "value": {
                      "project": {
                        "uuid": "d55e99b2-9ed3-4e68-b813-fbb0c283bec3",
                        "name": "example.com",
                        "created_at": "2020-02-11 04:27",
                        "owner": {
                          "id": 1,
                          "first_name": "Nhật",
                          "surname": "Đỗ",
                          "email": "nhat.do@nfq.asia",
                          "confirmed": true,
                          "extras": {
                            "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                          }
                        },
                        "extras": {
                          "num_of_images": 0,
                          "num_of_members": 1
                        }
                      },
                      "error": 0
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "description": "Add new project",
        "security": [
          {
            "API Token": []
          }
        ]
      },
      "parameters": []
    },
    "/api/v1/project/{uuid}/users/": {
      "get": {
        "tags": [
          "Project"
        ],
        "summary": "Project Members",
        "operationId": "ProjectMembers",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "owner": {
                      "$ref": "#/components/schemas/User"
                    },
                    "members": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/User"
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "value": {
                      "owner": {
                        "id": 1,
                        "firstName": "Nhật",
                        "surname": "Đỗ",
                        "email": "ddnhat@gmail.com",
                        "confirmed": true,
                        "extras": {
                          "gravatar": "24383f42136c8a5e7132a029a4b1e7db"
                        }
                      },
                      "members": [],
                      "error": 0
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": [
          {
            "API Token": []
          }
        ],
        "description": "List all members of this project"
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "uuid",
          "in": "path",
          "required": true,
          "description": "Project UUID"
        }
      ]
    },
    "/api/v1/project/{uuid}": {
      "post": {
        "tags": [
          "Project"
        ],
        "summary": "Project Detail",
        "operationId": "ProjectDetail",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "project": {
                      "$ref": "#/components/schemas/Project"
                    },
                    "error": {
                      "type": "number"
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "value": {
                      "project": {
                        "uuid": "014f045a-45d4-4d99-a9b1-432ad696b4ca",
                        "name": "tiki.vn",
                        "createdAt": "2020-02-03 07:55",
                        "owner": {
                          "id": 1,
                          "firstName": "Nhật",
                          "surname": "Đỗ",
                          "email": "ddnhat@gmail.com",
                          "confirmed": true,
                          "extras": {
                            "gravatar": "24383f42136c8a5e7132a029a4b1e7db"
                          }
                        },
                        "extras": []
                      },
                      "error": 0
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "description": "Get project info",
        "security": [
          {
            "API Token": []
          }
        ]
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "uuid",
          "in": "path",
          "required": true,
          "description": "Project UUID"
        }
      ]
    },
    "/api/v1/project/invite": {
      "post": {
        "tags": [
          "Project"
        ],
        "summary": "Invite User",
        "operationId": "InviteUser",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/InviteUserRequest"
              },
              "example": {
                "uuid": "0f67e1a0-0260-4dcf-b667-c8226d12d9a4",
                "emails": [
                  "doducnhat1990@gmail.com",
                  "dd.nhat@gmail.com"
                ]
              }
            }
          },
          "required": true,
          "x-send-file-in-body": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 1
                    }
                  },
                  "required": [
                    "error"
                  ]
                },
                "examples": {
                  "Success": {
                    "value": {
                      "error": 0
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": [
          {
            "API Token": []
          }
        ]
      },
      "parameters": []
    },
    "/api/v1/project/list": {
      "get": {
        "tags": [
          "Project"
        ],
        "summary": "Project List",
        "operationId": "ProjectList",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user_id": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Project"
                      }
                    },
                    "error": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 1
                    },
                    "message": {
                      "type": "string",
                      "description": "Present if there is any error"
                    },
                    "paginate": {
                      "$ref": "#/components/schemas/Pagination"
                    }
                  },
                  "required": [
                    "data",
                    "error"
                  ]
                },
                "examples": {
                  "Success": {
                    "value": {
                      "user_id": 1,
                      "data": [
                        {
                          "uuid": "b927be68-65c8-4c49-bba7-bc736dfe0de8",
                          "name": "test.com",
                          "createdAt": "2020-02-04 11:06",
                          "owner": {
                            "id": 1,
                            "firstName": "Nhật",
                            "surname": "Đỗ",
                            "email": "nhat.do@nfq.asia",
                            "confirmed": true,
                            "extras": {
                              "gavatar": "3fd6d6d6f23e1f44af6a52192556018a"
                            }
                          },
                          "extras": {
                            "canDelete": true,
                            "isAdmin": true,
                            "status": 1
                          }
                        }
                      ],
                      "pagination": {
                        "returned": 1,
                        "current_page": null,
                        "limit": 10,
                        "total": 1
                      },
                      "error": 0
                    }
                  },
                  "Failed": {
                    "value": {
                      "error": 1,
                      "msg": "Access Denied."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                },
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "message": "Username could not be found."
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "description": "List all projects",
        "requestBody": {},
        "security": [
          {
            "API Token": []
          }
        ]
      },
      "parameters": []
    },
    "/api/v1/image/upload": {
      "post": {
        "summary": "Upload Images",
        "operationId": "post-api-v1-image-upload",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 1
                    },
                    "files": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Image"
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "value": {
                      "files": [
                        {
                          "uuid": "967f7aee-d3ef-4e66-a439-b3d764c442a4",
                          "path": "1566994823183.jpg",
                          "project": {
                            "uuid": "c63df9ef-4711-4aed-8377-12cc24d25a81",
                            "name": "lazada.com.vn",
                            "created_at": "2020-02-05 09:03",
                            "owner": {
                              "id": 1,
                              "first_name": "Nhật",
                              "surname": "Đỗ",
                              "email": "nhat.do@nfq.asia",
                              "confirmed": true,
                              "extras": {
                                "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                              }
                            },
                            "extras": []
                          },
                          "owner": {
                            "id": 1,
                            "first_name": "Nhật",
                            "surname": "Đỗ",
                            "email": "nhat.do@nfq.asia",
                            "confirmed": true,
                            "extras": {
                              "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                            }
                          },
                          "tags": [],
                          "created_at": "2020-02-07 03:44"
                        },
                        {
                          "uuid": "12ec409b-d95e-444e-8a46-9510364c5c07",
                          "path": "1552455277257.jpg",
                          "project": {
                            "uuid": "c63df9ef-4711-4aed-8377-12cc24d25a81",
                            "name": "lazada.com.vn",
                            "created_at": "2020-02-05 09:03",
                            "owner": {
                              "id": 1,
                              "first_name": "Nhật",
                              "surname": "Đỗ",
                              "email": "nhat.do@nfq.asia",
                              "confirmed": true,
                              "extras": {
                                "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                              }
                            },
                            "extras": []
                          },
                          "owner": {
                            "id": 1,
                            "first_name": "Nhật",
                            "surname": "Đỗ",
                            "email": "nhat.do@nfq.asia",
                            "confirmed": true,
                            "extras": {
                              "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                            }
                          },
                          "tags": [],
                          "created_at": "2020-02-07 03:44"
                        },
                        {
                          "uuid": "b7cb6e5e-ab81-45db-8bd3-ed05d5daa661",
                          "path": "1552455274257.jpg",
                          "project": {
                            "uuid": "c63df9ef-4711-4aed-8377-12cc24d25a81",
                            "name": "lazada.com.vn",
                            "created_at": "2020-02-05 09:03",
                            "owner": {
                              "id": 1,
                              "first_name": "Nhật",
                              "surname": "Đỗ",
                              "email": "nhat.do@nfq.asia",
                              "confirmed": true,
                              "extras": {
                                "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                              }
                            },
                            "extras": []
                          },
                          "owner": {
                            "id": 1,
                            "first_name": "Nhật",
                            "surname": "Đỗ",
                            "email": "nhat.do@nfq.asia",
                            "confirmed": true,
                            "extras": {
                              "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                            }
                          },
                          "tags": [],
                          "created_at": "2020-02-07 03:44"
                        }
                      ],
                      "error": 0
                    }
                  },
                  "Error: FIles already existed": {
                    "value": {
                      "message": [
                        {
                          "file": "1566994823183.jpg",
                          "message": "This image \"1566994823183.jpg\" is already existed."
                        },
                        {
                          "file": "1552455277257.jpg",
                          "message": "This image \"1552455277257.jpg\" is already existed."
                        },
                        {
                          "file": "1552455274257.jpg",
                          "message": "This image \"1552455274257.jpg\" is already existed."
                        }
                      ],
                      "error": 1
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "API Token": []
          }
        ],
        "description": "Upload images",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/ImageUploadRequest"
              },
              "examples": {
                "Example": {
                  "value": {
                    "cURL": "curl --location --request POST 'http://imageserver.local/api/v1/image/upload' --form 'uuid=c63df9ef-4711-4aed-8377-12cc24d25a81' --form override=0' --form 'images[]=@/Users/doducnhat/Documents/Pictures/1552455277257.jpg' --form 'images[]=@/Users/doducnhat/Documents/Pictures/1552455274257.jpg'"
                  }
                }
              }
            }
          },
          "description": ""
        },
        "tags": [
          "Image"
        ]
      }
    },
    "/api/v1/image/{uuid}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "uuid",
          "in": "path",
          "required": true,
          "description": "Project UUID"
        }
      ],
      "get": {
        "summary": "Image List",
        "tags": [
          "Image"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Image"
                      }
                    },
                    "paginate": {
                      "$ref": "#/components/schemas/Pagination"
                    },
                    "error": {
                      "$ref": "#/components/schemas/Error"
                    }
                  },
                  "required": [
                    "error"
                  ]
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": [
                        {
                          "uuid": "52e9ec51-cfe8-4542-baba-4df7b21d274c",
                          "path": "1566994823183.jpg",
                          "project": {
                            "uuid": "fc1728a5-e169-41c0-8a26-f94ed35ca1e5",
                            "name": "tiki1.com.vn",
                            "created_at": "2020-02-10 05:58",
                            "owner": {
                              "id": 1,
                              "first_name": "Nhật",
                              "surname": "Đỗ",
                              "email": "nhat.do@nfq.asia",
                              "confirmed": true,
                              "extras": {
                                "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                              }
                            },
                            "extras": []
                          },
                          "owner": {
                            "id": 1,
                            "first_name": "Nhật",
                            "surname": "Đỗ",
                            "email": "nhat.do@nfq.asia",
                            "confirmed": true,
                            "extras": {
                              "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                            }
                          },
                          "tags": [],
                          "created_at": "2020-02-10 05:58"
                        },
                        {
                          "uuid": "4db69d05-ef00-40a6-999a-df11046de213",
                          "path": "1552455277257.jpg",
                          "project": {
                            "uuid": "fc1728a5-e169-41c0-8a26-f94ed35ca1e5",
                            "name": "tiki1.com.vn",
                            "created_at": "2020-02-10 05:58",
                            "owner": {
                              "id": 1,
                              "first_name": "Nhật",
                              "surname": "Đỗ",
                              "email": "nhat.do@nfq.asia",
                              "confirmed": true,
                              "extras": {
                                "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                              }
                            },
                            "extras": []
                          },
                          "owner": {
                            "id": 1,
                            "first_name": "Nhật",
                            "surname": "Đỗ",
                            "email": "nhat.do@nfq.asia",
                            "confirmed": true,
                            "extras": {
                              "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                            }
                          },
                          "tags": [],
                          "created_at": "2020-02-10 05:58"
                        },
                        {
                          "uuid": "4b5bb0d1-6c71-403e-a8b9-0437d9cd9613",
                          "path": "1552455274257.jpg",
                          "project": {
                            "uuid": "fc1728a5-e169-41c0-8a26-f94ed35ca1e5",
                            "name": "tiki1.com.vn",
                            "created_at": "2020-02-10 05:58",
                            "owner": {
                              "id": 1,
                              "first_name": "Nhật",
                              "surname": "Đỗ",
                              "email": "nhat.do@nfq.asia",
                              "confirmed": true,
                              "extras": {
                                "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                              }
                            },
                            "extras": []
                          },
                          "owner": {
                            "id": 1,
                            "first_name": "Nhật",
                            "surname": "Đỗ",
                            "email": "nhat.do@nfq.asia",
                            "confirmed": true,
                            "extras": {
                              "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                            }
                          },
                          "tags": [],
                          "created_at": "2020-02-10 05:58"
                        }
                      ],
                      "pagination": {
                        "returned": 3,
                        "current_page": 1,
                        "limit": 50,
                        "total": 3
                      },
                      "error": 0
                    }
                  },
                  "Invalid UUID": {
                    "value": {
                      "message": "Project not found",
                      "error": 1
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-api-v1-image-uuid",
        "description": "List all images in the project",
        "security": [
          {
            "API Token": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "s",
            "description": "Search images by tag name. Separated by comma"
          }
        ]
      }
    }
  },
  "tags": [
    {
      "name": "Project"
    }
  ],
  "security": [
    {
      "auth-token": []
    }
  ],
  "components": {
    "schemas": {
      "InviteUserRequest": {
        "title": "InviteUserRequest",
        "required": [
          "uuid",
          "emails"
        ],
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "emails": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "uuid": "0f67e1a0-0260-4dcf-b667-c8226d12d9a4",
          "emails": [
            "doducnhat1990@gmail.com",
            "dd.nhat@gmail.com"
          ]
        }
      },
      "CreateProjectRequest": {
        "title": "CreateProjectRequest",
        "type": "object",
        "example": {
          "name": "example.com"
        },
        "x-examples": {},
        "properties": {
          "name": {
            "type": "string",
            "format": "hostname"
          }
        },
        "required": [
          "name"
        ]
      },
      "DeleteProjectRequest": {
        "title": "DeleteProjectRequest",
        "required": [
          "uuid"
        ],
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          }
        },
        "example": {
          "uuid": "0f67e1a0-0260-4dcf-b667-c8226d12d9a4"
        }
      },
      "LeaveProjectRequest": {
        "title": "LeaveProjectRequest",
        "required": [
          "uuid"
        ],
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          }
        },
        "example": {
          "uuid": "0f67e1a0-0260-4dcf-b667-c8226d12d9a4"
        }
      },
      "User": {
        "title": "User",
        "type": "object",
        "x-examples": {
          "User": {
            "id": 1,
            "firstName": "John",
            "surname": "Doe",
            "email": "john.doe@imageserver.test",
            "confirmed": true,
            "extras": {
              "gavatar": "3fd6d6d6f23e1f44af6a52192556018a"
            }
          }
        },
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 0
          },
          "firstname": {
            "type": "string"
          },
          "surname": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "confirmed": {
            "type": "boolean"
          },
          "extras": {
            "type": "object",
            "properties": {
              "gravatar": {
                "type": "string",
                "minLength": 32,
                "maxLength": 32,
                "pattern": "^[A-Za-z0-9]+"
              }
            }
          }
        },
        "required": [
          "id",
          "firstname",
          "surname",
          "email",
          "confirmed",
          "extras"
        ]
      },
      "Pagination": {
        "title": "Pagination",
        "type": "object",
        "properties": {
          "returned": {
            "type": "integer",
            "minimum": 0
          },
          "current_page": {
            "type": "integer",
            "default": 1,
            "minimum": 0
          },
          "limit": {
            "type": "integer",
            "default": 10,
            "minimum": 1
          },
          "total": {
            "type": "integer",
            "minimum": 1
          }
        },
        "required": [
          "returned",
          "current_page",
          "limit",
          "total"
        ],
        "x-examples": {}
      },
      "Project": {
        "title": "Project",
        "type": "object",
        "x-examples": {
          "Project": {
            "uuid": "d55e99b2-9ed3-4e68-b813-fbb0c283bec3",
            "name": "example.com",
            "created_at": "2020-02-11 04:27",
            "owner": {
              "id": 1,
              "first_name": "Nhật",
              "surname": "Đỗ",
              "email": "nhat.do@nfq.asia",
              "confirmed": true,
              "extras": {
                "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
              }
            },
            "extras": {
              "can_delete": true,
              "is_admin": true,
              "status": 1,
              "num_of_images": 4,
              "num_of_members": 2
            }
          }
        },
        "description": "",
        "properties": {
          "uuid": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "owner": {
            "$ref": "#/components/schemas/User"
          },
          "extras": {
            "type": "object",
            "properties": {
              "can_delete": {
                "type": "boolean"
              },
              "is_admin": {
                "type": "boolean"
              },
              "status": {
                "type": "integer",
                "minimum": 0,
                "maximum": 1
              },
              "num_of_images": {
                "type": "integer",
                "minimum": 0
              },
              "num_of_members": {
                "type": "integer",
                "minimum": 0
              }
            }
          }
        },
        "required": [
          "uuid",
          "name",
          "created_at",
          "owner",
          "extras"
        ]
      },
      "ImageUploadRequest": {
        "title": "ImageUploadRequest",
        "type": "object",
        "x-examples": {
          "Example": {
            "cURL": "curl --location --request POST 'http://imageserver.local/api/v1/image/upload' --form 'uuid=c63df9ef-4711-4aed-8377-12cc24d25a81' --form override=0' --form 'images[]=@/Users/doducnhat/Documents/Pictures/1552455277257.jpg' --form 'images[]=@/Users/doducnhat/Documents/Pictures/1552455274257.jpg'"
          }
        },
        "properties": {
          "uuid": {
            "type": "string",
            "format": "uuid",
            "description": "Project UUID"
          },
          "images[]": {
            "type": "array",
            "description": "Array of binary images. \nimages[]: new formData() [javascript]",
            "items": {
              "type": "binary"
            }
          },
          "override": {
            "type": "integer",
            "minimum": 0,
            "maximum": 1,
            "description": "Override Images\n0: don't override\n1: force override"
          }
        },
        "required": [
          "uuid",
          "images[]"
        ]
      },
      "Image": {
        "title": "Image",
        "type": "object",
        "x-examples": {
          "Image": {
            "uuid": "967f7aee-d3ef-4e66-a439-b3d764c442a4",
            "path": "1566994823183.jpg",
            "project": {
              "uuid": "c63df9ef-4711-4aed-8377-12cc24d25a81",
              "name": "lazada.com.vn",
              "created_at": "2020-02-05 09:03",
              "owner": {
                "id": 1,
                "first_name": "Nhật",
                "surname": "Đỗ",
                "email": "nhat.do@nfq.asia",
                "confirmed": true,
                "extras": {
                  "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
                }
              },
              "extras": []
            },
            "owner": {
              "id": 1,
              "first_name": "Nhật",
              "surname": "Đỗ",
              "email": "nhat.do@nfq.asia",
              "confirmed": true,
              "extras": {
                "gravatar": "3fd6d6d6f23e1f44af6a52192556018a"
              }
            },
            "tags": [],
            "created_at": "2020-02-07 03:44"
          }
        },
        "properties": {
          "uuid": {
            "type": "string"
          },
          "path": {
            "type": "string"
          },
          "project": {
            "$ref": "#/components/schemas/Project"
          },
          "owner": {
            "$ref": "#/components/schemas/User"
          },
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Tag"
            }
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          }
        },
        "required": [
          "uuid",
          "path",
          "project",
          "owner",
          "tags",
          "created_at"
        ],
        "description": ""
      },
      "Error": {
        "title": "Error",
        "description": "",
        "type": "object",
        "properties": {
          "error": {
            "type": "integer",
            "minimum": 0,
            "maximum": 1
          },
          "message": {
            "type": [
              "string",
              "array"
            ],
            "items": {
              "type": [
                "string",
                "object"
              ]
            }
          }
        },
        "required": [
          "error"
        ],
        "x-examples": {
          "Success": {
            "error": 0
          },
          "Failed": {
            "error": 1,
            "message": "Project Not Found"
          }
        }
      },
      "Tag": {
        "title": "Tag",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          }
        },
        "required": [
          "name",
          "created_at"
        ]
      }
    },
    "securitySchemes": {
      "API Token": {
        "type": "apiKey",
        "description": "User Access Token",
        "name": "x-auth-token",
        "in": "header"
      }
    }
  }
}